<!-- Filepond -->
<link rel="stylesheet" href="https://unpkg.com/filepond/dist/filepond.css">
<link href="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.css" rel="stylesheet">